## RNNS
$$
P(x_t \mid x_{t-1}, \dots, x_1) \approx P(x_t \mid h_{t-1})
$$
- $ht = f(x_t, ht-1)$
$$
\mathbf{H}_t = \phi(\mathbf{X}_t \mathbf{W}_{xh} + \mathbf{H}_{t-1} \mathbf{W}_{hh} + \mathbf{b}_h)
$$

- Hidden state uses same definition as prev time step in the current time step. Thus computation is recurrent. hence recurrent layers and  neural network



In [2]:
import torch
from d2l import torch as d2l

In [5]:
# can get 
X, W_xh = torch.randn(3, 1), torch.randn(1, 4)
H, W_hh = torch.randn(3, 4), torch.randn(4, 4)
print(torch.matmul(X, W_xh) + torch.matmul(H, W_hh)) # size 3,  4 as expected
print(torch.matmul(torch.cat((X, H), dim=1), torch.cat((W_xh, W_hh), dim=0))) # same res as above

tensor([[-1.0355, -0.3764, -2.6309,  0.7753],
        [-1.6885, -1.9384,  0.3852,  0.7754],
        [ 1.4346, -1.8717,  6.5223,  0.7529]])
tensor([[-1.0355, -0.3764, -2.6309,  0.7753],
        [-1.6885, -1.9384,  0.3852,  0.7754],
        [ 1.4346, -1.8717,  6.5223,  0.7529]])


tensor([[ 0.9163,  1.1414, -0.4810,  0.7046, -0.0820],
        [ 1.7890,  0.6371,  0.4074, -0.7482, -0.0399],
        [-1.0555, -1.7106,  0.8202, -1.8226, -1.0724]])