In [1]:
import torch
from torch import nn
from torch.nn import functional as F
from d2l import torch as d2l

In [3]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, X):
        return X - X.mean()

In [6]:
layer = CenteredLayer()
layer(torch.tensor([10.0, 20, 30, 40 , 50]))  # mean is 30

tensor([-20., -10.,   0.,  10.,  20.])

In [13]:
net = nn.Sequential(nn.LazyLinear(128), CenteredLayer())
Y = net(torch.rand(4, 8))
Y.mean()

tensor(-1.3970e-09, grad_fn=<MeanBackward0>)

In [15]:
# layers with params
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [17]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.9258,  0.2198,  0.9197],
        [-1.8278, -0.4663, -2.6554],
        [ 1.1808, -2.0480,  0.0488],
        [-1.7783, -1.9512,  1.0482],
        [-0.9705, -0.0554, -0.5167]], requires_grad=True)

In [20]:
linear(torch.rand(2, 5))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [21]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[3.7052],
        [0.0000]])